name: Deploy Spring Boot to Azure for sample learning project

on:
  push:
    branches:
      - main  # Adjust based on your workflow
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:


      - name: Set Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check Azure Subscription
        run: az account show

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: 'SERVICE_PRINCIPAL'
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Login to ACR
        run: az acr login --name <BACKEND_ACR_NAME>

      - name: Build & Push Docker Image to ACR
        run: |
          docker build -t <BACKEND_ACR_NAME>.azurecr.io/backend-app:${{ github.sha }} .
          docker push <BACKEND_ACR_NAME>.azurecr.io/backend-app:${{ github.sha }}

      - name: Deploy Container to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'satya-learning-backend'
          images: '<BACKEND_ACR_NAME>.azurecr.io/backend-app:${{ github.sha }}'